filebeat.modules:
- module: logstash
filebeat.inputs:
- type: log
  paths:
    - /var/log/messages
    - /var/log/*.log
#----------------------------- Logstash output --------------------------------
output.logstash:
  hosts: ["graylog:5044"]
